webapp:
  vault:
    authPath: auth/k8s-golddr # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald

  route:
    host: uat-ride.apps.golddr.devops.gov.bc.ca

frontend:
  route:
    host: uat-ride-frontend.apps.golddr.devops.gov.bc.ca # The host name for the route. Ensure set to golddr for the Gold DR cluster.
  vault:
    authPath: auth/k8s-golddr # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald