apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}-allow-static
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Release.Name }}-static
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.fullname" . }}
  policyTypes:
    - Ingress
